### ISSUE TITLE
"Invalid App Identifier"

### ISSUE THREAD

**Issue by nwittwer** [RudyRosciglione/Pancake#16]
===AUTHENTICATION ERROR===
Error Domain=com.spotify.auth Code=0 "invalid_app_identifier" UserInfo={NSLocalizedDescription=invalid_app_identifier}

This is probably a rookie mistake on my part but would appreciate help.

**Comment by avazquezpr** [comment]
Will check issue when i get home.

**Comment by avazquezpr** [comment]
Do you have Spotify installed in your phone? If so try uninstalling it and then opening Pancake. It should take you to online login. Please let me know so we can work on a fix :)

**Comment by nwittwer** [comment]
Ah, that fixed it! Thanks! Let me know if you guys need a bug reporter/beta tester/designer/front-end guy :)

**Comment by RudyRosciglione** [comment]
@nwittwer - Well at the time we are good with design and front-end guy but you can join the facebook group to be involve with bug reporter + beta test : https://www.facebook.com/groups/PancakeCommunity

**Comment by nathanandersen** [comment]
Hello

This wasn't an issue with Pancake, it is actually an ongoing issue with Spotify.
