### ISSUE TITLE
Login troubles

### ISSUE THREAD

**Issue by RudyRosciglione** [RudyRosciglione/Pancake#3]
There is several issue with login : 

1. When you run the app and if you aren’t login you will see the dashboardViewCrontroller before the loginViewControler. It’s very quick but it visible.
2. When you success login with spotify, you are invite to come back on the application, but instead to see the DashboardViewControler, you see an empty screen. It's funny because when you will close the app and you come back you will get the DashboardViewControler. 

You can always clone the project on your machine and make your pull request. If you think you can improve the code. Maybe open Safary directly in the application would be better.

**Comment by DWilliames** [comment]
To fix the first past so that the dashboardViewController isn't visible, I set the "newUser" segue Animates status to "No". This way it will segue straight to the LoginViewController without showing the dashboardViewController.

**Comment by DWilliames** [comment]
Please see my Pull Request as to how these issues can be solved.
