### ISSUE TITLE
UILabel with multiple fonts at the same time

### ISSUE THREAD

**Issue by RudyRosciglione** [RudyRosciglione/Pancake#4]
On the dashboardViewController there is the time displayed and i wish to have AM/PM a way smaller that the time as the design preview.

![screen home](https://cloud.githubusercontent.com/assets/1166152/12196663/d9bd9832-b600-11e5-91c4-8937701a7c72.png)
<img width="432" alt="screen shot 2016-01-08 at 12 03 38" src="https://cloud.githubusercontent.com/assets/1166152/12196667/e3e49112-b600-11e5-9860-2a262a2920a2.png">

You can always clone the project on your machine and make your pull request. If you think you can improve the code. <3

**Comment by steffex** [comment]
Option 1:
Use autolayout to have a smaller label attach to the big label with the digits.

Option 2:
Use an attributed string, this allows for advanced label markup.

**Comment by damtsnkff** [comment]
I'd have say option 1 too. Could be done really quickly.

**Comment by avazquezpr** [comment]
Issue solved in Pull Request #7. Used @steffex suggestion and created another label that is attached to the timeDisplay label using AutoLayout constraints.
